project 'IntracloudWeather.xcodeproj'

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'IntracloudWeather' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for IntracloudWeather
pod 'MMDrawerController', '~> 0.5.7'
pod 'SDWebImage', '~> 3.8'
pod 'MJRefresh', '~> 3.1'
pod 'FMDB', '~> 2.6.2'
pod 'AFNetworking', '~> 3.1'
pod 'MBProgressHUD', '~> 1.0'
end
